package edu.uiuc.cs427app.data.entity;

import androidx.annotation.NonNull;
import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.Index;
import androidx.room.PrimaryKey;

import java.io.Serializable;
import java.util.Date;
import java.util.UUID;

@Entity(tableName = "user", indices = {
        @Index(value = {"email"}, unique = true)
})
public class User implements Serializable {
    @PrimaryKey
    @NonNull
    private UUID id;

    @ColumnInfo(name = "login_name")
    @NonNull
    private String loginName;

    @ColumnInfo(name = "email")
    @NonNull
    private String emailId;

    @NonNull
    private String password;

    @ColumnInfo(name = "is_logged_in")
    private Boolean loggedIn;

    @ColumnInfo(name = "last_logged_in")
    private Date lastLoggedIn;

    @ColumnInfo(name = "current_theme")
    private Integer currentTheme;

    @ColumnInfo(name = "created_on")
    private Date createdOn;

    @ColumnInfo(name = "last_modified")
    private Date lastModified;

    /**
     * Create new user instance.
     * The user id is autogenerated.
     */
    public User() {
        this.id = UUID.randomUUID();
    }

    /**
     * @return user id
     */
    @NonNull
    public UUID getId() {
        return id;
    }

    /**
     * Set user id
     * Warning: user id is automatically generated when creating a new user and trying to set a value
     * manually for the id can throw violation errors when saving the user to the DB.
     * Currently, there is no way to hide this as the Room library needs public getters and setters for all fields
     * @param id user id
     */
    public void setId(@NonNull UUID id) {
        this.id = id;
    }

    /**
     * @return user login name
     */
    @NonNull
    public String getLoginName() {
        return loginName;
    }

    /**
     * Set user login name
     * @param loginName user login name
     */
    public void setLoginName(@NonNull String loginName) {
        this.loginName = loginName;
    }

    /**
     * @return user email
     */
    @NonNull
    public String getEmailId() {
        return emailId;
    }

    /**
     * Set user email
     * @param emailId new email id
     */
    public void setEmailId(@NonNull String emailId) {
        this.emailId = emailId;
    }

    /**
     * @return user password
     */
    @NonNull
    public String getPassword() {
        return password;
    }

    /**
     * Set user password
     * @param password user password
     */
    public void setPassword(@NonNull String password) {
        this.password = password;
    }

    /**
     * @return flag indicating if user is logged in
     */
    public Boolean getLoggedIn() {
        return loggedIn;
    }

    /**
     * Set user logged in flag
     * @param loggedIn true or false
     */
    public void setLoggedIn(Boolean loggedIn) {
        this.loggedIn = loggedIn;
    }

    /**
     * @return user last logged in date
     */
    public Date getLastLoggedIn() {
        return lastLoggedIn;
    }

    /**
     * Set date when user last logged in
     * @param lastLoggedIn last logged in date
     */
    public void setLastLoggedIn(Date lastLoggedIn) {
        this.lastLoggedIn = lastLoggedIn;
    }

    /**
     * @return user's selected theme
     */
    public Integer getCurrentTheme() {
        return currentTheme;
    }

    /**
     * Set user's selected theme
     * @param currentTheme theme identifier
     */
    public void setCurrentTheme(Integer currentTheme) {
        this.currentTheme = currentTheme;
    }

    /**
     * @return user created date
     */
    public Date getCreatedOn() {
        return createdOn;
    }

    /**
     * Set user created on date
     * @param createdOn created date
     */
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    /**
     * @return date when user details were last modified
     */
    public Date getLastModified() {
        return lastModified;
    }

    /**
     * Set user last modified date.
     * This should be set when modifying other user fields.
     * @param lastModified last modified
     */
    public void setLastModified(Date lastModified) {
        this.lastModified = lastModified;
    }
}
